// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiNIH3pLEsf8-KxHz2jOxht1oxargn7WA',
    appId: '1:1044656055952:android:fcedcbf694db3768d41a15',
    messagingSenderId: '1044656055952',
    projectId: 'quetame-turismo',
    storageBucket: 'quetame-turismo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgjTkPvmWGsQheitBJan9H4SOa0-dkT3A',
    appId: '1:1044656055952:ios:48fdc013f9813b02d41a15',
    messagingSenderId: '1044656055952',
    projectId: 'quetame-turismo',
    storageBucket: 'quetame-turismo.firebasestorage.app',
    iosBundleId: 'com.example.quetameTurismo',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDqno-E4dYWOi6EOHhQ4-iBZxy766tu6M',
    appId: '1:1044656055952:web:751514a8aceb273fd41a15',
    messagingSenderId: '1044656055952',
    projectId: 'quetame-turismo',
    authDomain: 'quetame-turismo.firebaseapp.com',
    storageBucket: 'quetame-turismo.firebasestorage.app',
    measurementId: 'G-25KSD1BT9W',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgjTkPvmWGsQheitBJan9H4SOa0-dkT3A',
    appId: '1:1044656055952:ios:48fdc013f9813b02d41a15',
    messagingSenderId: '1044656055952',
    projectId: 'quetame-turismo',
    storageBucket: 'quetame-turismo.firebasestorage.app',
    iosBundleId: 'com.example.quetameTurismo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDqno-E4dYWOi6EOHhQ4-iBZxy766tu6M',
    appId: '1:1044656055952:web:90d9a13c88a7b4fad41a15',
    messagingSenderId: '1044656055952',
    projectId: 'quetame-turismo',
    authDomain: 'quetame-turismo.firebaseapp.com',
    storageBucket: 'quetame-turismo.firebasestorage.app',
    measurementId: 'G-KBJ15362LS',
  );

}